import type { ItemDefinition, ItemRarity } from '@/types'

export const ITEM_CATALOG: Record<string, ItemDefinition> = {
  // ── COMMON (60% of drops) ─────────────────────────────────
  ketchup_packet: {
    itemKey: 'ketchup_packet',
    name: 'Ketchup Packet',
    description: 'Heal 20 HP to your active card',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 20,
    flavorText: 'Stolen from a fast food counter. The good stuff.',
  },
  mustard_squirt: {
    itemKey: 'mustard_squirt',
    name: 'Mustard Squirt',
    description: 'Boost ATK by +5 for 3 turns',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 5,
    effectDuration: 3,
    flavorText: 'Dijon? Yellow? Who cares — it burns with power.',
  },
  stale_bun_shield: {
    itemKey: 'stale_bun_shield',
    name: 'Stale Bun Shield',
    description: 'Boost DEF by +8 for 3 turns',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 8,
    effectDuration: 3,
    flavorText: 'Hard as a rock. Perfect for blocking attacks.',
  },
  relish_boost: {
    itemKey: 'relish_boost',
    name: 'Relish Boost',
    description: 'Boost SPD by +5 for 3 turns',
    rarity: 'common',
    effectType: 'buff_spd',
    effectValue: 5,
    effectDuration: 3,
    flavorText: 'Sweet, tangy, and surprisingly aerodynamic.',
  },
  onion_ring: {
    itemKey: 'onion_ring',
    name: 'Onion Ring',
    description: 'Heal 15 HP to your active card',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 15,
    flavorText: 'A perfect golden circle of fried comfort.',
  },
  paper_napkin: {
    itemKey: 'paper_napkin',
    name: 'Paper Napkin',
    description: 'Boost DEF by +4 for 3 turns',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 4,
    effectDuration: 3,
    flavorText: 'Surprisingly absorbent. Blocks grease-based attacks.',
  },
  toothpick_lance: {
    itemKey: 'toothpick_lance',
    name: 'Toothpick Lance',
    description: 'Deal 10 direct damage (ignores defense)',
    rarity: 'common',
    effectType: 'direct_damage',
    effectValue: 10,
    flavorText: 'Tiny but pointy. Aim for the gaps.',
  },
  fizzy_cola: {
    itemKey: 'fizzy_cola',
    name: 'Fizzy Cola',
    description: 'Boost SPD by +8 for 2 turns',
    rarity: 'common',
    effectType: 'buff_spd',
    effectValue: 8,
    effectDuration: 2,
    flavorText: 'Sugar rush incoming. Effects may vary.',
  },
  pickle_slice: {
    itemKey: 'pickle_slice',
    name: 'Pickle Slice',
    description: 'Boost ATK by +3 for 4 turns',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 3,
    effectDuration: 4,
    flavorText: 'Crunchy, briny, and full of fighting spirit.',
  },
  salt_shaker: {
    itemKey: 'salt_shaker',
    name: 'Salt Shaker',
    description: 'Lower opponent ATK by -3 for 3 turns',
    rarity: 'common',
    effectType: 'debuff_atk',
    effectValue: 3,
    effectDuration: 3,
    flavorText: 'Throw salt at your problems. Literally.',
  },
  bbq_drizzle: {
    itemKey: 'bbq_drizzle',
    name: 'BBQ Drizzle',
    description: 'Boost ATK by +4 for 3 turns',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 4,
    effectDuration: 3,
    flavorText: 'Smoky, sweet, and slightly sticky on the fingers.',
  },
  bread_crust: {
    itemKey: 'bread_crust',
    name: 'Bread Crust',
    description: 'Heal 10 HP to your active card',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 10,
    flavorText: 'Nobody wants it. But it does the job.',
  },
  hot_sauce_drop: {
    itemKey: 'hot_sauce_drop',
    name: 'Hot Sauce Drop',
    description: 'Deal 8 direct damage (ignores defense)',
    rarity: 'common',
    effectType: 'direct_damage',
    effectValue: 8,
    flavorText: 'Just a single drop. That is more than enough.',
  },
  cheese_slice: {
    itemKey: 'cheese_slice',
    name: 'Cheese Slice',
    description: 'Boost DEF by +6 for 2 turns',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 6,
    effectDuration: 2,
    flavorText: 'Processed, plastic-wrapped, and surprisingly protective.',
  },

  // ── UNCOMMON (30% of drops) ───────────────────────────────
  jalapeno_stick: {
    itemKey: 'jalapeno_stick',
    name: 'Jalapeño Stick',
    description: 'Deal 25 direct damage (ignores defense)',
    rarity: 'uncommon',
    effectType: 'direct_damage',
    effectValue: 25,
    flavorText: 'Handle with gloves. Or don\'t — we\'re not your mom.',
  },
  grease_splash: {
    itemKey: 'grease_splash',
    name: 'Grease Splash',
    description: 'Lower opponent DEF by -8 for 3 turns',
    rarity: 'uncommon',
    effectType: 'debuff_def',
    effectValue: 8,
    effectDuration: 3,
    flavorText: 'Collected from the bottom of the grill. Slippery.',
  },
  sauerkraut_wrap: {
    itemKey: 'sauerkraut_wrap',
    name: 'Sauerkraut Wrap',
    description: 'Heal 40 HP to your active card',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 40,
    flavorText: 'Fermented cabbage heals all wounds. Science says so.',
  },
  curry_powder_bomb: {
    itemKey: 'curry_powder_bomb',
    name: 'Curry Powder Bomb',
    description: 'Deal 15 damage + lower ATK by -5 for 3 turns',
    rarity: 'uncommon',
    effectType: 'debuff_atk',
    effectValue: 5,
    effectDuration: 3,
    flavorText: 'A cloud of spice that makes eyes water and muscles weak.',
  },
  grill_tongs: {
    itemKey: 'grill_tongs',
    name: 'Grill Tongs',
    description: 'Boost ATK by +10 for 2 turns',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 10,
    effectDuration: 2,
    flavorText: 'Click click. The universal sign of grill authority.',
  },
  smoked_paprika: {
    itemKey: 'smoked_paprika',
    name: 'Smoked Paprika',
    description: 'Deal 20 direct damage (ignores defense)',
    rarity: 'uncommon',
    effectType: 'direct_damage',
    effectValue: 20,
    flavorText: 'The smoky burn that sneaks up on you.',
  },
  pretzel_armor: {
    itemKey: 'pretzel_armor',
    name: 'Pretzel Armor',
    description: 'Boost DEF by +12 for 2 turns',
    rarity: 'uncommon',
    effectType: 'buff_def',
    effectValue: 12,
    effectDuration: 2,
    flavorText: 'Twisted into an impenetrable knot of salty defense.',
  },
  energy_drink: {
    itemKey: 'energy_drink',
    name: 'Energy Drink',
    description: 'Boost SPD by +10 for 3 turns',
    rarity: 'uncommon',
    effectType: 'buff_spd',
    effectValue: 10,
    effectDuration: 3,
    flavorText: 'Questionable ingredients. Undeniable speed.',
  },
  mayo_bomb: {
    itemKey: 'mayo_bomb',
    name: 'Mayo Bomb',
    description: 'Lower opponent SPD by -8 for 3 turns',
    rarity: 'uncommon',
    effectType: 'debuff_def',
    effectValue: 8,
    effectDuration: 3,
    flavorText: 'Thick, white, and devastatingly slippery.',
  },
  bratwurst_band_aid: {
    itemKey: 'bratwurst_band_aid',
    name: 'Bratwurst Band-Aid',
    description: 'Heal 35 HP to your active card',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 35,
    flavorText: 'Made from real bratwurst casing. FDA has questions.',
  },
  ghost_pepper: {
    itemKey: 'ghost_pepper',
    name: 'Ghost Pepper',
    description: 'Deal 30 direct damage (ignores defense)',
    rarity: 'uncommon',
    effectType: 'direct_damage',
    effectValue: 30,
    flavorText: 'Over a million Scoville units of pure regret.',
  },
  vinegar_splash: {
    itemKey: 'vinegar_splash',
    name: 'Vinegar Splash',
    description: 'Lower opponent ATK by -8 for 3 turns',
    rarity: 'uncommon',
    effectType: 'debuff_atk',
    effectValue: 8,
    effectDuration: 3,
    flavorText: 'The smell alone is enough to weaken anyone.',
  },
  charcoal_rub: {
    itemKey: 'charcoal_rub',
    name: 'Charcoal Rub',
    description: 'Boost ATK by +7 for 3 turns',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 7,
    effectDuration: 3,
    flavorText: 'Black as night, hot as embers, strong as steel.',
  },
  soda_can_grenade: {
    itemKey: 'soda_can_grenade',
    name: 'Soda Can Grenade',
    description: 'Deal 18 damage + lower DEF by -5 for 2 turns',
    rarity: 'uncommon',
    effectType: 'debuff_def',
    effectValue: 5,
    effectDuration: 2,
    flavorText: 'Shake vigorously before throwing. Stand back.',
  },

  // ── RARE (10% of drops) ───────────────────────────────────
  golden_bratwurst: {
    itemKey: 'golden_bratwurst',
    name: 'Golden Bratwurst',
    description: 'Heal 60 HP to your active card',
    rarity: 'rare',
    effectType: 'heal',
    effectValue: 60,
    flavorText: 'Legend says it was grilled by the gods themselves.',
  },
  forbidden_condiment: {
    itemKey: 'forbidden_condiment',
    name: 'The Forbidden Condiment',
    description: 'Deal 40 direct damage (ignores defense)',
    rarity: 'rare',
    effectType: 'direct_damage',
    effectValue: 40,
    flavorText: 'No one knows the recipe. Those who tasted it never spoke again.',
  },
  diamond_skewer: {
    itemKey: 'diamond_skewer',
    name: 'Diamond Skewer',
    description: 'Deal 50 direct damage (ignores defense)',
    rarity: 'rare',
    effectType: 'direct_damage',
    effectValue: 50,
    flavorText: 'Forged from compressed sausage grease over millennia.',
  },
  truffle_oil: {
    itemKey: 'truffle_oil',
    name: 'Truffle Oil',
    description: 'Boost ATK by +15 for 3 turns',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 15,
    effectDuration: 3,
    flavorText: 'Expensive, pretentious, and devastatingly effective.',
  },
  titanium_tray: {
    itemKey: 'titanium_tray',
    name: 'Titanium Tray',
    description: 'Boost DEF by +20 for 3 turns',
    rarity: 'rare',
    effectType: 'buff_def',
    effectValue: 20,
    effectDuration: 3,
    flavorText: 'Originally from a military mess hall. Indestructible.',
  },
  dragon_hot_sauce: {
    itemKey: 'dragon_hot_sauce',
    name: 'Dragon Hot Sauce',
    description: 'Deal 35 damage + lower DEF by -10 for 3 turns',
    rarity: 'rare',
    effectType: 'debuff_def',
    effectValue: 10,
    effectDuration: 3,
    flavorText: 'Brewed in an active volcano. Probably.',
  },
  wagyu_wrap: {
    itemKey: 'wagyu_wrap',
    name: 'Wagyu Wrap',
    description: 'Heal 80 HP to your active card',
    rarity: 'rare',
    effectType: 'heal',
    effectValue: 80,
    flavorText: 'A5 grade healing. Your card has never felt this good.',
  },
  nitro_coffee: {
    itemKey: 'nitro_coffee',
    name: 'Nitro Coffee',
    description: 'Boost SPD by +20 for 3 turns',
    rarity: 'rare',
    effectType: 'buff_spd',
    effectValue: 20,
    effectDuration: 3,
    flavorText: 'Time slows down. Or you speed up. Same difference.',
  },
  ancient_marinade: {
    itemKey: 'ancient_marinade',
    name: 'Ancient Marinade',
    description: 'Lower opponent ATK by -15 for 3 turns',
    rarity: 'rare',
    effectType: 'debuff_atk',
    effectValue: 15,
    effectDuration: 3,
    flavorText: 'Recipe found in a tomb. The pharaohs knew their BBQ.',
  },
  sausage_kings_crown: {
    itemKey: 'sausage_kings_crown',
    name: 'Sausage King\'s Crown',
    description: 'Boost ATK by +8 and DEF by +8 for 3 turns',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 8,
    effectDuration: 3,
    flavorText: 'Worn by the legendary Sausage King of Chicago. All hail.',
  },
  meteor_pepper: {
    itemKey: 'meteor_pepper',
    name: 'Meteor Pepper',
    description: 'Deal 45 direct damage (ignores defense)',
    rarity: 'rare',
    effectType: 'direct_damage',
    effectValue: 45,
    flavorText: 'Fell from space. Tastes like the end of the world.',
  },
  elixir_of_grill: {
    itemKey: 'elixir_of_grill',
    name: 'Elixir of Grill',
    description: 'Heal 70 HP to your active card',
    rarity: 'rare',
    effectType: 'heal',
    effectValue: 70,
    flavorText: 'Liquid smoke, ancient herbs, and a hint of magic.',
  },
}

const COMMON_ITEMS = Object.values(ITEM_CATALOG).filter(i => i.rarity === 'common')
const UNCOMMON_ITEMS = Object.values(ITEM_CATALOG).filter(i => i.rarity === 'uncommon')
const RARE_ITEMS = Object.values(ITEM_CATALOG).filter(i => i.rarity === 'rare')

const DROP_CHANCE = 0.18

const RARITY_WEIGHTS: { rarity: ItemRarity; weight: number; items: ItemDefinition[] }[] = [
  { rarity: 'common', weight: 60, items: COMMON_ITEMS },
  { rarity: 'uncommon', weight: 30, items: UNCOMMON_ITEMS },
  { rarity: 'rare', weight: 10, items: RARE_ITEMS },
]

export function rollItemDrop(): ItemDefinition | null {
  if (Math.random() > DROP_CHANCE) return null

  const roll = Math.random() * 100
  let cumulative = 0
  for (const tier of RARITY_WEIGHTS) {
    cumulative += tier.weight
    if (roll < cumulative) {
      const item = tier.items[Math.floor(Math.random() * tier.items.length)]
      return item
    }
  }

  return COMMON_ITEMS[0]
}

export function getItemDefinition(itemKey: string): ItemDefinition | undefined {
  return ITEM_CATALOG[itemKey]
}

export function getItemsByRarity(rarity: string): ItemDefinition[] {
  return Object.values(ITEM_CATALOG).filter(item => item.rarity === rarity)
}
