import type { StarterCard } from '@/theme/types'

export const STARTER_CARDS: StarterCard[] = [
  {
    heroTitle: 'Soggy Microwave Frank',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 45, attack: 15, defense: 10, speed: 8,
    specialMoves: ['Lukewarm Splash (25/10)', 'Sad Sizzle (35/5)', 'Ketchup Drizzle (45/2)'],
    weakness: 'Any form of seasoning',
    catchphrase: 'I was frozen five minutes ago...',
    flavorText: 'Found behind the office microwave. Still slightly cold in the middle.',
    weekKey: 'STARTER-1',
  },
  {
    heroTitle: 'The Uncooked Rookie',
    heroType: 'BRATWURST/VEGGIE',
    hp: 40, attack: 10, defense: 20, speed: 6,
    specialMoves: ['Raw Slap (20/15)', 'Refrigerator Chill (30/6)', 'Expiry Date Panic (40/3)'],
    weakness: 'Room temperature',
    catchphrase: 'Please... just cook me...',
    flavorText: 'Straight out of the package with the little absorbent pad still attached.',
    weekKey: 'STARTER-2',
  },
  {
    heroTitle: 'Leftover Link',
    heroType: 'KIELBASA/BLOOD_SAUSAGE',
    hp: 50, attack: 12, defense: 12, speed: 15,
    specialMoves: ['Day-Old Toss (20/12)', 'Suspicious Smell (30/6)', 'Microwave Spin (40/3)'],
    weakness: 'Being sniffed before eating',
    catchphrase: 'I was great yesterday, I swear!',
    flavorText: 'Three days in the back of the fridge. Character building.',
    weekKey: 'STARTER-3',
  },
  {
    heroTitle: 'Bargain Bin Banger',
    heroType: 'ANDOUILLE/SAUERKRAUT',
    hp: 35, attack: 18, defense: 8, speed: 12,
    specialMoves: ['Discount Slam (30/8)', 'Shrink-Wrap Shield (20/12)', 'Best Before Blitz (45/2)'],
    weakness: 'Quality control',
    catchphrase: '50% off and worth every penny!',
    flavorText: 'The yellow sticker special. Questionable origin, unbeatable price.',
    weekKey: 'STARTER-4',
  },
  {
    heroTitle: 'Mystery Meat Cylinder',
    heroType: 'CURRYWURST/CHORIZO',
    hp: 55, attack: 8, defense: 15, speed: 5,
    specialMoves: ['Ambiguous Ooze (20/15)', 'Label Confusion (35/5)', 'Preservative Burst (45/2)'],
    weakness: 'Ingredient lists',
    catchphrase: 'You don\'t want to know what\'s inside...',
    flavorText: 'Contents: meat (probably). May contain traces of everything.',
    weekKey: 'STARTER-5',
  },
]
