import type { StarterCard } from '@/theme/types'

export const STARTER_CARDS: StarterCard[] = [
  {
    heroTitle: 'Soggy Microwave Frank',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 45, attack: 15, defense: 10, speed: 8,
    specialMoves: ['Lukewarm Splash (25/10)', 'Sad Sizzle (35/5)', 'Ketchup Drizzle (45/2)'],
    weakness: 'Any form of seasoning',
    catchphrase: 'I was frozen five minutes ago...',
    flavorText: 'Found behind the office microwave. Still slightly cold in the middle.',
    weekKey: 'STARTER-1',
  },
  {
    heroTitle: 'The Uncooked Rookie',
    heroType: 'BRATWURST/VEGGIE',
    hp: 40, attack: 10, defense: 20, speed: 6,
    specialMoves: ['Raw Slap (20/15)', 'Refrigerator Chill (30/6)', 'Expiry Date Panic (40/3)'],
    weakness: 'Room temperature',
    catchphrase: 'Please... just cook me...',
    flavorText: 'Straight out of the package with the little absorbent pad still attached.',
    weekKey: 'STARTER-2',
  },
  {
    heroTitle: 'Leftover Link',
    heroType: 'KIELBASA/BLOOD_SAUSAGE',
    hp: 50, attack: 12, defense: 12, speed: 15,
    specialMoves: ['Day-Old Toss (20/12)', 'Suspicious Smell (30/6)', 'Microwave Spin (40/3)'],
    weakness: 'Being sniffed before eating',
    catchphrase: 'I was great yesterday, I swear!',
    flavorText: 'Three days in the back of the fridge. Character building.',
    weekKey: 'STARTER-3',
  },
  {
    heroTitle: 'Bargain Bin Banger',
    heroType: 'ANDOUILLE/SAUERKRAUT',
    hp: 35, attack: 18, defense: 8, speed: 12,
    specialMoves: ['Discount Slam (30/8)', 'Shrink-Wrap Shield (20/12)', 'Best Before Blitz (45/2)'],
    weakness: 'Quality control',
    catchphrase: '50% off and worth every penny!',
    flavorText: 'The yellow sticker special. Questionable origin, unbeatable price.',
    weekKey: 'STARTER-4',
  },
  {
    heroTitle: 'Mystery Meat Cylinder',
    heroType: 'CURRYWURST/CHORIZO',
    hp: 55, attack: 8, defense: 15, speed: 5,
    specialMoves: ['Ambiguous Ooze (20/15)', 'Label Confusion (35/5)', 'Preservative Burst (45/2)'],
    weakness: 'Ingredient lists',
    catchphrase: 'You don\'t want to know what\'s inside...',
    flavorText: 'Contents: meat (probably). May contain traces of everything.',
    weekKey: 'STARTER-5',
  },
  {
    heroTitle: 'Gas Station Roller Dog',
    heroType: 'FRANKFURTER/CHORIZO',
    hp: 60, attack: 20, defense: 10, speed: 5,
    specialMoves: ['Eternal Rotation (15/12)', 'Grease Slide (30/6)', 'Questionable Snap (40/3)'],
    weakness: 'Health inspectors',
    catchphrase: 'I\'ve been spinning since Tuesday.',
    flavorText: 'Has been rotating on those metal rollers for an unknowable amount of time. Resilient.',
    weekKey: 'STARTER-6',
  },
  {
    heroTitle: 'The Burnt End',
    heroType: 'BRATWURST/KIELBASA',
    hp: 40, attack: 25, defense: 5, speed: 10,
    specialMoves: ['Charcoal Crunch (35/5)', 'Ash Cloud (20/8)', 'Carbon Coating (30/6)'],
    weakness: 'Already destroyed by fire',
    catchphrase: 'I\'m not burnt, I\'m CRISPY.',
    flavorText: 'Left on the grill too long. Dad says it\'s "fine." It is not fine.',
    weekKey: 'STARTER-7',
  },
  {
    heroTitle: 'Cocktail Weenie Wayne',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 30, attack: 8, defense: 8, speed: 20,
    specialMoves: ['Toothpick Stab (15/12)', 'Party Platter Dash (25/7)', 'Tiny But Fierce (35/4)'],
    weakness: 'Literally the smallest sausage at the party',
    catchphrase: 'Size doesn\'t matter! ...right?',
    flavorText: 'Wrapped in a crescent roll and feeling overdressed. The appetizer nobody asked for.',
    weekKey: 'STARTER-8',
  },
  {
    heroTitle: 'The Veggie Imposter',
    heroType: 'VEGGIE/BRATWURST',
    hp: 50, attack: 10, defense: 18, speed: 12,
    specialMoves: ['Soy Surprise (20/8)', 'Textured Confusion (30/5)', 'Protein Question (25/7)'],
    weakness: 'Being compared to the real thing',
    catchphrase: 'I taste JUST like meat! (narrator: it didn\'t)',
    flavorText: 'Trying its best. Has fooled exactly zero people but earned their pity.',
    weekKey: 'STARTER-9',
  },
  {
    heroTitle: 'The Bun Escaper',
    heroType: 'BRATWURST/ANDOUILLE',
    hp: 45, attack: 15, defense: 12, speed: 18,
    specialMoves: ['Ketchup Slide (25/7)', 'Mustard Skid (20/8)', 'Bun Break (35/4)'],
    weakness: 'Cannot stay in a bun to save its life',
    catchphrase: 'You can\'t contain me!',
    flavorText: 'Every bite sends it shooting out the back of the bun. A hot dog that refuses to cooperate.',
    weekKey: 'STARTER-10',
  },
  {
    heroTitle: 'Fancy Artisan Sausage',
    heroType: 'CHORIZO/SAUERKRAUT',
    hp: 35, attack: 12, defense: 15, speed: 8,
    specialMoves: ['Truffle Dust (20/8)', 'Organic Label (15/10)', 'Farm-to-Table Flex (35/4)'],
    weakness: 'Being served at a BBQ like a commoner',
    catchphrase: 'I\'m hand-crafted with heritage pork.',
    flavorText: 'Costs $14 for one link. Comes from a butcher who wears a handlebar mustache.',
    weekKey: 'STARTER-11',
  },
  {
    heroTitle: 'Freezer Burn Barry',
    heroType: 'KIELBASA/FRANKFURTER',
    hp: 55, attack: 10, defense: 20, speed: 5,
    specialMoves: ['Ice Crystal Blast (25/6)', 'Frost Armor (15/10)', 'Defrost Delay (30/5)'],
    weakness: 'Has been in the freezer since 2019',
    catchphrase: 'I\'m still good! Check the date... actually, don\'t.',
    flavorText: 'Found behind the ice cream during a freezer clean-out. Covered in mysterious frost.',
    weekKey: 'STARTER-12',
  },
  {
    heroTitle: 'The Condiment Hog',
    heroType: 'MUSTARD/CURRYWURST',
    hp: 40, attack: 15, defense: 10, speed: 15,
    specialMoves: ['Mustard Tsunami (30/5)', 'Relish Flood (20/8)', 'Onion Avalanche (35/4)'],
    weakness: 'You can\'t see the sausage under all the toppings',
    catchphrase: 'More mustard. MORE.',
    flavorText: 'There\'s a sausage somewhere under that mountain of condiments. Probably.',
    weekKey: 'STARTER-13',
  },
  {
    heroTitle: 'Split Casing Sally',
    heroType: 'BRATWURST/KIELBASA',
    hp: 35, attack: 22, defense: 5, speed: 15,
    specialMoves: ['Juice Squirt (30/5)', 'Casing Whip (20/8)', 'Burst Blast (40/3)'],
    weakness: 'Structural integrity',
    catchphrase: 'I\'m falling apart and I LIKE IT.',
    flavorText: 'Casing split on the grill. Juices everywhere. A beautiful disaster.',
    weekKey: 'STARTER-14',
  },
  {
    heroTitle: 'The Forgotten Fridge Frank',
    heroType: 'FRANKFURTER/BLOOD_SAUSAGE',
    hp: 50, attack: 8, defense: 18, speed: 5,
    specialMoves: ['Green Spot Surprise (25/6)', 'Fridge Stench (30/5)', 'Expiry Gamble (40/3)'],
    weakness: 'Anyone with a functioning nose',
    catchphrase: 'I\'m vintage, not expired.',
    flavorText: 'Pushed to the very back of the fridge. Has developed a personality and possibly sentience.',
    weekKey: 'STARTER-15',
  },
  {
    heroTitle: 'Hot Dog Water Harry',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 45, attack: 12, defense: 15, speed: 10,
    specialMoves: ['Broth Splash (20/8)', 'Soggy Soak (15/10)', 'Lukewarm Lob (30/5)'],
    weakness: 'Nobody wants to drink him',
    catchphrase: 'I\'m technically a broth.',
    flavorText: 'The water frankfurters are boiled in. Claims to be "stock." He is not stock.',
    weekKey: 'STARTER-16',
  },
  {
    heroTitle: 'Sauerkraut Steve',
    heroType: 'SAUERKRAUT/KIELBASA',
    hp: 50, attack: 15, defense: 20, speed: 8,
    specialMoves: ['Fermented Fury (25/6)', 'Brine Splash (20/8)', 'Probiotic Shield (15/10)'],
    weakness: 'People who think he\'s just cabbage',
    catchphrase: 'I\'m CULTURED. Literally.',
    flavorText: 'Fermented for weeks. Has more culture than most people. Smells like it too.',
    weekKey: 'STARTER-17',
  },
  {
    heroTitle: 'The Dropped Dog',
    heroType: 'FRANKFURTER/BRATWURST',
    hp: 30, attack: 10, defense: 8, speed: 18,
    specialMoves: ['Five Second Rule (20/8)', 'Floor Bounce (15/10)', 'Gravel Crunch (30/5)'],
    weakness: 'Gravity',
    catchphrase: 'The five second rule is SCIENCE.',
    flavorText: 'Fell off the plate at the BBQ. Was picked up, dusted off, and served anyway.',
    weekKey: 'STARTER-18',
  },
  {
    heroTitle: 'Overloaded Oscar',
    heroType: 'BRATWURST/SAUERKRAUT',
    hp: 55, attack: 18, defense: 10, speed: 5,
    specialMoves: ['Topping Cascade (30/5)', 'Structural Collapse (35/4)', 'Napkin Emergency (20/7)'],
    weakness: 'Cannot be eaten without making a mess',
    catchphrase: 'One of everything, please.',
    flavorText: 'Sauerkraut, onions, mustard, relish, cheese, jalapeños. More topping than sausage.',
    weekKey: 'STARTER-19',
  },
  {
    heroTitle: 'The Boiled Bore',
    heroType: 'FRANKFURTER/KIELBASA',
    hp: 60, attack: 8, defense: 15, speed: 8,
    specialMoves: ['Bland Blast (15/10)', 'Tepid Splash (20/8)', 'Water-Logged Whack (25/6)'],
    weakness: 'Flavor of any kind',
    catchphrase: 'Grilling is overrated.',
    flavorText: 'Just boiled. No char, no grill marks, no personality. Served with sadness.',
    weekKey: 'STARTER-20',
  },
  {
    heroTitle: 'Stadium Dog Doug',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 40, attack: 15, defense: 10, speed: 15,
    specialMoves: ['Overpriced Punch ($12/5)', 'Crowd Surf (25/6)', 'Seventh Inning Stretch (20/8)'],
    weakness: 'Costs $12 and worth $0.50',
    catchphrase: 'I\'m a PREMIUM hot dog experience.',
    flavorText: 'A $0.50 hot dog in a $12 wrapper. The markup is the real crime.',
    weekKey: 'STARTER-21',
  },
  {
    heroTitle: 'Corn Dog Carl',
    heroType: 'FRANKFURTER/ANDOUILLE',
    hp: 45, attack: 18, defense: 15, speed: 10,
    specialMoves: ['Batter Bash (25/6)', 'Stick Stab (30/5)', 'Deep Fry Fury (40/3)'],
    weakness: 'The stick always gets in the way',
    catchphrase: 'I\'m a sausage in disguise!',
    flavorText: 'A frankfurter that went undercover in a cornmeal jacket. Fair food legend.',
    weekKey: 'STARTER-22',
  },
  {
    heroTitle: 'The Unturned',
    heroType: 'BRATWURST/CHORIZO',
    hp: 35, attack: 20, defense: 8, speed: 10,
    specialMoves: ['Half-Raw Surprise (30/5)', 'Black Bottom (25/6)', 'Flip Flop (35/4)'],
    weakness: 'Whoever forgot to turn them',
    catchphrase: 'One side perfect, one side raw. That\'s LIFE.',
    flavorText: 'Grillmaster walked away. Now it\'s charcoal on one side, pink on the other.',
    weekKey: 'STARTER-23',
  },
  {
    heroTitle: 'The Chain Link',
    heroType: 'KIELBASA/BRATWURST',
    hp: 50, attack: 12, defense: 12, speed: 12,
    specialMoves: ['Link Lash (20/8)', 'Chain Reaction (30/5)', 'Separation Anxiety (25/7)'],
    weakness: 'Being torn apart from siblings',
    catchphrase: 'We\'re stronger together!',
    flavorText: 'Still connected to 11 other sausages. Refuses to be separated. Co-dependent.',
    weekKey: 'STARTER-24',
  },
  {
    heroTitle: 'Currywurst Klaus',
    heroType: 'CURRYWURST/MUSTARD',
    hp: 45, attack: 20, defense: 10, speed: 12,
    specialMoves: ['Curry Powder Cloud (25/6)', 'Ketchup Curry Combo (30/5)', 'Berlin Blitz (40/3)'],
    weakness: 'Purists who say it\'s not real food',
    catchphrase: 'I am Germany\'s greatest invention!',
    flavorText: 'Cut into pieces, drowned in curry ketchup. A Berlin street food icon.',
    weekKey: 'STARTER-25',
  },
  {
    heroTitle: 'The Squeaker',
    heroType: 'BRATWURST/VEGGIE',
    hp: 40, attack: 10, defense: 15, speed: 15,
    specialMoves: ['Casing Squeak (15/10)', 'Embarrassing Sound (20/8)', 'Bite Noise (25/6)'],
    weakness: 'Every bite makes an awkward sound',
    catchphrase: '*squeak squeak squeak*',
    flavorText: 'The casing squeaks against your teeth. Everyone at the table heard it.',
    weekKey: 'STARTER-26',
  },
  {
    heroTitle: 'Kid\'s Party Patty',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 35, attack: 8, defense: 10, speed: 18,
    specialMoves: ['Ketchup Smiley (15/10)', 'Octopus Cut (20/8)', 'Bun Too Big (25/6)'],
    weakness: 'Only edible when cut into fun shapes',
    catchphrase: 'I\'m an octopus! Wheee!',
    flavorText: 'Cut to look like a little octopus for a 6-year-old\'s birthday. Peak culinary art.',
    weekKey: 'STARTER-27',
  },
  {
    heroTitle: 'The Street Vendor',
    heroType: 'CHORIZO/FRANKFURTER',
    hp: 50, attack: 18, defense: 12, speed: 10,
    specialMoves: ['Cart Rush (25/6)', 'Umbrella Shield (20/8)', 'Cash Only Confusion (30/5)'],
    weakness: 'Rain and health department visits',
    catchphrase: 'One dollar! Hot dog one dollar!',
    flavorText: 'That cart has been on the same corner since 1987. The umbrella has seen things.',
    weekKey: 'STARTER-28',
  },
  {
    heroTitle: 'Deep Fried Disaster',
    heroType: 'ANDOUILLE/CURRYWURST',
    hp: 40, attack: 22, defense: 8, speed: 8,
    specialMoves: ['Oil Splash (30/5)', 'Batter Bomb (25/6)', 'Grease Lightning (40/3)'],
    weakness: 'Arteries',
    catchphrase: 'Everything is better deep fried!',
    flavorText: 'Someone deep fried a sausage. Then battered it. Then deep fried it again. County fair legend.',
    weekKey: 'STARTER-29',
  },
  {
    heroTitle: 'The Escaped Sausage',
    heroType: 'BRATWURST/SPEED',
    hp: 30, attack: 10, defense: 5, speed: 25,
    specialMoves: ['Grill Dodge (15/10)', 'Tong Evade (20/8)', 'Gap Fall (25/6)'],
    weakness: 'Falls through the grill grates',
    catchphrase: 'FREEDOM! *falls into coals*',
    flavorText: 'Slipped through the grill grates. Now it\'s a charcoal fossil. RIP.',
    weekKey: 'STARTER-30',
  },
  {
    heroTitle: 'Cheese-Stuffed Charles',
    heroType: 'BRATWURST/MUSTARD',
    hp: 50, attack: 20, defense: 15, speed: 8,
    specialMoves: ['Molten Cheese Burst (35/4)', 'Cheddar Shield (20/7)', 'Gouda Gush (30/5)'],
    weakness: 'The cheese is LAVA temperature',
    catchphrase: 'Surprise! I\'m full of cheese!',
    flavorText: 'Looks normal on the outside. Bite in and get third-degree mouth burns from molten cheddar.',
    weekKey: 'STARTER-31',
  },
  {
    heroTitle: 'The Lone Sausage',
    heroType: 'KIELBASA/BLOOD_SAUSAGE',
    hp: 55, attack: 12, defense: 18, speed: 8,
    specialMoves: ['Last One Standing (25/6)', 'Lonely Chill (15/10)', 'Solo Roll (20/8)'],
    weakness: 'Being the last sausage nobody wants',
    catchphrase: 'Someone will pick me eventually... right?',
    flavorText: 'The last sausage on the plate. Everyone saw it, nobody wants to be "that person."',
    weekKey: 'STARTER-32',
  },
  {
    heroTitle: 'BBQ Sauce Bandit',
    heroType: 'ANDOUILLE/CHORIZO',
    hp: 45, attack: 18, defense: 10, speed: 12,
    specialMoves: ['Sticky Slap (25/6)', 'Sauce Drip (20/8)', 'Smoky Haze (30/5)'],
    weakness: 'Makes everything sticky',
    catchphrase: 'BBQ sauce goes on EVERYTHING.',
    flavorText: 'Covered in so much BBQ sauce it\'s basically a dessert. Your hands will never be clean.',
    weekKey: 'STARTER-33',
  },
  {
    heroTitle: 'The Double Dog',
    heroType: 'FRANKFURTER/FRANKFURTER',
    hp: 50, attack: 22, defense: 8, speed: 10,
    specialMoves: ['Twin Strike (30/5)', 'Double Trouble (35/4)', 'Bun Overflow (25/6)'],
    weakness: 'Too wide for any bun',
    catchphrase: 'Why have one when you can have TWO?',
    flavorText: 'Two franks in one bun. An act of beautiful excess. The bun can\'t handle it.',
    weekKey: 'STARTER-34',
  },
  {
    heroTitle: 'Pretzel Bun Paul',
    heroType: 'BRATWURST/SAUERKRAUT',
    hp: 45, attack: 15, defense: 18, speed: 10,
    specialMoves: ['Salt Crystal Throw (20/8)', 'Doughy Defense (15/10)', 'Pretzel Twist (30/5)'],
    weakness: 'Gets overshadowed by the bun',
    catchphrase: 'It\'s about the BUN, baby.',
    flavorText: 'Nobody remembers the sausage. Everyone remembers the pretzel bun. Paul knows his place.',
    weekKey: 'STARTER-35',
  },
  {
    heroTitle: 'The Chicago Dog',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 45, attack: 15, defense: 12, speed: 15,
    specialMoves: ['Sport Pepper Poke (25/6)', 'Neon Green Assault (30/5)', 'No Ketchup Rule (20/8)'],
    weakness: 'Mention ketchup and he loses it',
    catchphrase: 'If you put ketchup on me, we\'re DONE.',
    flavorText: 'Mustard, onions, relish, tomato, pickle, sport peppers, celery salt. NO KETCHUP. Ever.',
    weekKey: 'STARTER-36',
  },
  {
    heroTitle: 'Spotted Dick',
    heroType: 'BLOOD_SAUSAGE/KIELBASA',
    hp: 55, attack: 10, defense: 20, speed: 5,
    specialMoves: ['British Confusion (20/8)', 'Suet Shield (15/10)', 'Pudding Plop (30/5)'],
    weakness: 'Nobody knows what he actually is',
    catchphrase: 'I\'m a PUDDING, not a sausage! ...or am I?',
    flavorText: 'Technically a pudding but somehow ended up in the sausage battle arena. Confused but game.',
    weekKey: 'STARTER-37',
  },
  {
    heroTitle: 'The Skinless Wonder',
    heroType: 'FRANKFURTER/VEGGIE',
    hp: 40, attack: 12, defense: 8, speed: 15,
    specialMoves: ['Smooth Slide (20/8)', 'No Snap (15/10)', 'Pale Punch (25/6)'],
    weakness: 'Zero structural integrity without casing',
    catchphrase: 'I\'m more... aerodynamic this way.',
    flavorText: 'No casing, no snap, no texture. Just vibes and a vaguely cylindrical shape.',
    weekKey: 'STARTER-38',
  },
  {
    heroTitle: 'IKEA Hot Dog Ingrid',
    heroType: 'FRANKFURTER/MUSTARD',
    hp: 35, attack: 10, defense: 10, speed: 20,
    specialMoves: ['Flat Pack Smack (20/8)', 'Checkout Sprint (25/6)', 'Lost Instructions (30/5)'],
    weakness: 'Only costs $1 so expectations are very low',
    catchphrase: 'I cost less than a KALLAX shelf bracket!',
    flavorText: 'The only reason anyone goes to IKEA. Reward yourself after assembling a MALM.',
    weekKey: 'STARTER-39',
  },
  {
    heroTitle: 'The Regret Dog',
    heroType: 'FRANKFURTER/ANDOUILLE',
    hp: 45, attack: 15, defense: 10, speed: 12,
    specialMoves: ['2am Shame (25/6)', 'Indigestion Wave (30/5)', 'Morning After (35/4)'],
    weakness: 'The post-eating guilt',
    catchphrase: 'You knew this was a mistake and you did it anyway.',
    flavorText: 'Eaten at 2am from a dubious street cart. Seemed like a great idea at the time.',
    weekKey: 'STARTER-40',
  },
  {
    heroTitle: 'The Cocktail Sausage Ring',
    heroType: 'FRANKFURTER/SAUERKRAUT',
    hp: 50, attack: 10, defense: 20, speed: 8,
    specialMoves: ['Circle Formation (15/10)', 'Pineapple Cheese Hedge (20/8)', 'Retro Party (30/5)'],
    weakness: 'Only appears at parties from the 1970s',
    catchphrase: 'I\'m the centerpiece and I KNOW it.',
    flavorText: 'Cocktail sausages on sticks arranged in a ring on a tinfoil-covered pineapple. Classy.',
    weekKey: 'STARTER-41',
  },
  {
    heroTitle: 'Pigs in Blankets Pete',
    heroType: 'FRANKFURTER/BRATWURST',
    hp: 40, attack: 18, defense: 15, speed: 10,
    specialMoves: ['Bacon Wrap (25/6)', 'Pastry Roll (20/8)', 'Christmas Dinner Crash (35/4)'],
    weakness: 'Only relevant one month per year',
    catchphrase: 'It\'s not Christmas without ME.',
    flavorText: 'A sausage wrapped in bacon. The undisputed star of Christmas dinner. Turkey who?',
    weekKey: 'STARTER-42',
  },
  {
    heroTitle: 'Andouille André',
    heroType: 'ANDOUILLE/CHORIZO',
    hp: 50, attack: 20, defense: 12, speed: 10,
    specialMoves: ['Cajun Kick (30/5)', 'Gumbo Slam (25/6)', 'Bayou Splash (35/4)'],
    weakness: 'People who pronounce it "an-DOO-eel"',
    catchphrase: 'It\'s ahn-DOO-ee, you uncultured swine.',
    flavorText: 'From the bayou with attitude. Smoky, spicy, and tired of being mispronounced.',
    weekKey: 'STARTER-43',
  },
  {
    heroTitle: 'The Tofu Dog',
    heroType: 'VEGGIE/MUSTARD',
    hp: 45, attack: 8, defense: 20, speed: 12,
    specialMoves: ['Guilt Trip (20/8)', 'Plant Protein Punch (25/6)', 'Moral High Ground (15/10)'],
    weakness: 'Literally any real sausage',
    catchphrase: 'I\'m saving the planet, one bite at a time.',
    flavorText: 'Tastes like sadness and good intentions. Your vegan friend brought it to the BBQ.',
    weekKey: 'STARTER-44',
  },
  {
    heroTitle: 'The Casing Connoisseur',
    heroType: 'KIELBASA/BRATWURST',
    hp: 50, attack: 15, defense: 15, speed: 10,
    specialMoves: ['Natural Casing Snap (25/6)', 'Collagen Crunch (20/8)', 'Intestine Knowledge (30/5)'],
    weakness: 'Learning where natural casings actually come from',
    catchphrase: 'You can HEAR the quality in the snap.',
    flavorText: 'Can identify a natural casing by sound alone. Don\'t ask them to explain what it\'s made of.',
    weekKey: 'STARTER-45',
  },
  {
    heroTitle: 'Piccalilli Penny',
    heroType: 'MUSTARD/SAUERKRAUT',
    hp: 40, attack: 12, defense: 15, speed: 15,
    specialMoves: ['Tangy Toss (20/8)', 'Pickle Patch (25/6)', 'Relish Drizzle (30/5)'],
    weakness: 'Nobody under 60 knows what she is',
    catchphrase: 'I\'m a CLASSIC condiment, thank you.',
    flavorText: 'A condiment from another era. Your grandma loved her. You\'re not entirely sure what she is.',
    weekKey: 'STARTER-46',
  },
  {
    heroTitle: 'The Spiralizer',
    heroType: 'BRATWURST/CURRYWURST',
    hp: 45, attack: 18, defense: 10, speed: 12,
    specialMoves: ['Spiral Slash (25/6)', 'Curl Cut (20/8)', 'Tornado Dog (35/4)'],
    weakness: 'Falls apart when spiralized too aggressively',
    catchphrase: 'I\'m art on a stick!',
    flavorText: 'Cut into a spiral and deep fried on a stick. State fair technology at its finest.',
    weekKey: 'STARTER-47',
  },
  {
    heroTitle: 'Lunchbox Larry',
    heroType: 'FRANKFURTER/KIELBASA',
    hp: 45, attack: 10, defense: 15, speed: 12,
    specialMoves: ['Thermos Throw (20/8)', 'Warm-ish Attack (25/6)', 'Zip Lock Shield (15/10)'],
    weakness: 'Has been in a lunchbox since 7am. It\'s now 1pm.',
    catchphrase: 'I\'m still good! The ice pack is only mostly melted.',
    flavorText: 'Packed this morning with love. Now room temperature with regret.',
    weekKey: 'STARTER-48',
  },
  {
    heroTitle: 'The Wrong Order',
    heroType: 'CHORIZO/FRANKFURTER',
    hp: 40, attack: 15, defense: 12, speed: 15,
    specialMoves: ['Confusion Strike (25/6)', 'Receipt Check (20/8)', 'Send It Back (30/5)'],
    weakness: 'Nobody actually ordered this',
    catchphrase: 'Wait... this isn\'t what I ordered?',
    flavorText: 'You ordered a bratwurst. You got this. Too awkward to send it back. Acceptance.',
    weekKey: 'STARTER-49',
  },
  {
    heroTitle: 'Tupperware Tim',
    heroType: 'KIELBASA/ANDOUILLE',
    hp: 55, attack: 10, defense: 20, speed: 5,
    specialMoves: ['Lid Lock (15/10)', 'Reheat Ray (25/6)', 'Leftover Lob (30/5)'],
    weakness: 'The lid never fits properly',
    catchphrase: 'I\'ll be even better tomorrow. Trust me.',
    flavorText: 'Leftover sausage in a Tupperware that doesn\'t quite close. Leaking in the work fridge.',
    weekKey: 'STARTER-50',
  },
]
