import type { ItemDefinition } from '@/types'

export const exerciseItemCatalog: Record<string, ItemDefinition> = {
  // === COMMON (14) ===
  protein_bar: {
    itemKey: 'protein_bar',
    name: 'Protein Bar',
    description: 'Restores 20 HP. Tastes like chocolate-flavored cardboard.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 20,
    flavorText: '30g of protein, 0g of flavor. Gains don\'t care about your taste buds.',
  },
  water_bottle: {
    itemKey: 'water_bottle',
    name: 'Water Bottle',
    description: 'Restores 15 HP. Stay hydrated, king.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 15,
    flavorText: 'A gallon jug that\'s definitely compensating for something.',
  },
  resistance_band: {
    itemKey: 'resistance_band',
    name: 'Resistance Band',
    description: 'Boosts ATK by 8 for 2 turns.',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 8,
    effectDuration: 2,
    flavorText: 'Snap risk adds an element of danger to every rep.',
  },
  sweatband: {
    itemKey: 'sweatband',
    name: 'Sweatband',
    description: 'Boosts SPD by 10 for 2 turns.',
    rarity: 'common',
    effectType: 'buff_spd',
    effectValue: 10,
    effectDuration: 2,
    flavorText: 'Nothing says "I\'m serious" like a retro headband.',
  },
  chalk_bag: {
    itemKey: 'chalk_bag',
    name: 'Chalk Bag',
    description: 'Boosts ATK by 10 for 1 turn. Better grip = bigger lifts.',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 10,
    effectDuration: 1,
    flavorText: 'Leaves a cloud of white dust and a trail of broken PRs.',
  },
  jump_rope: {
    itemKey: 'jump_rope',
    name: 'Jump Rope',
    description: 'Deals 12 direct damage. Skip to the pain.',
    rarity: 'common',
    effectType: 'direct_damage',
    effectValue: 12,
    flavorText: 'Double-unders: the move that humbles even the strongest bros.',
  },
  foam_roller_slice: {
    itemKey: 'foam_roller_slice',
    name: 'Foam Roller Slice',
    description: 'Boosts DEF by 8 for 2 turns.',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 8,
    effectDuration: 2,
    flavorText: 'Hurts so good. Recovery is gains, right? RIGHT?',
  },
  towel_snap: {
    itemKey: 'towel_snap',
    name: 'Towel Snap',
    description: 'Deals 10 direct damage. Locker room warfare.',
    rarity: 'common',
    effectType: 'direct_damage',
    effectValue: 10,
    flavorText: 'A weapon perfected in middle school, deployed in the iron temple.',
  },
  grip_tape: {
    itemKey: 'grip_tape',
    name: 'Grip Tape',
    description: 'Boosts ATK by 6 for 3 turns.',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 6,
    effectDuration: 3,
    flavorText: 'Because your grip gave out before your ego did.',
  },
  wrist_wrap: {
    itemKey: 'wrist_wrap',
    name: 'Wrist Wrap',
    description: 'Boosts DEF by 6 for 3 turns.',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 6,
    effectDuration: 3,
    flavorText: 'Protects your wrists so you can keep scrolling between sets.',
  },
  knee_sleeve: {
    itemKey: 'knee_sleeve',
    name: 'Knee Sleeve',
    description: 'Boosts DEF by 10 for 2 turns.',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 10,
    effectDuration: 2,
    flavorText: 'Your knees sound like bubble wrap. This helps. Barely.',
  },
  athletic_tape: {
    itemKey: 'athletic_tape',
    name: 'Athletic Tape',
    description: 'Restores 12 HP. Duct tape for athletes.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 12,
    flavorText: 'If it\'s taped, it\'s healed. That\'s how anatomy works.',
  },
  sports_drink: {
    itemKey: 'sports_drink',
    name: 'Sports Drink',
    description: 'Restores 18 HP. Electrolytes, bro.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 18,
    flavorText: 'It\'s what gains crave. It\'s got electrolytes.',
  },
  ammonia_salt: {
    itemKey: 'ammonia_salt',
    name: 'Ammonia Salt',
    description: 'Boosts ATK by 12 for 1 turn. WAKE UP.',
    rarity: 'common',
    effectType: 'buff_atk',
    effectValue: 12,
    effectDuration: 1,
    flavorText: 'One sniff and you could deadlift a bus. Side effects include screaming.',
  },

  energy_gel: {
    itemKey: 'energy_gel',
    name: 'Energy Gel',
    description: 'Restores 18 HP. Tastes like syrup, hits like caffeine.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 18,
    flavorText: 'Squeeze it into your mouth mid-stride like a pro. Try not to gag.',
  },
  running_socks: {
    itemKey: 'running_socks',
    name: 'Anti-Blister Socks',
    description: 'Boosts SPD by 8 for 2 turns. Happy feet, fast feet.',
    rarity: 'common',
    effectType: 'buff_spd',
    effectValue: 8,
    effectDuration: 2,
    flavorText: 'The difference between a good run and a trip to the pharmacy.',
  },
  cycling_gloves: {
    itemKey: 'cycling_gloves',
    name: 'Cycling Gloves',
    description: 'Boosts DEF by 8 for 2 turns. Padded palms, protected pride.',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 8,
    effectDuration: 2,
    flavorText: 'Half-finger gloves so you can still unlock your phone mid-ride.',
  },
  reflective_vest: {
    itemKey: 'reflective_vest',
    name: 'Reflective Vest',
    description: 'Boosts DEF by 10 for 2 turns. Visible and invincible.',
    rarity: 'common',
    effectType: 'buff_def',
    effectValue: 10,
    effectDuration: 2,
    flavorText: 'You look ridiculous but at least cars can see you at 5am.',
  },
  pace_band: {
    itemKey: 'pace_band',
    name: 'Pace Band',
    description: 'Boosts SPD by 10 for 1 turn. Know your splits.',
    rarity: 'common',
    effectType: 'buff_spd',
    effectValue: 10,
    effectDuration: 1,
    flavorText: 'A wristband that tells you you\'re too slow. Motivational.',
  },
  trail_mix: {
    itemKey: 'trail_mix',
    name: 'Trail Mix',
    description: 'Restores 15 HP. Raisins are the price you pay for the M&Ms.',
    rarity: 'common',
    effectType: 'heal',
    effectValue: 15,
    flavorText: 'Nobody eats the raisins. Nobody.',
  },

  // === UNCOMMON (11) ===
  pre_workout_powder: {
    itemKey: 'pre_workout_powder',
    name: 'Pre-Workout Powder',
    description: 'Boosts ATK by 15 and SPD by 10 for 2 turns.',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 15,
    effectDuration: 2,
    flavorText: 'Two scoops and you can see sounds. Three scoops and you ARE the workout.',
  },
  compression_sleeves: {
    itemKey: 'compression_sleeves',
    name: 'Compression Sleeves',
    description: 'Boosts DEF by 15 for 3 turns.',
    rarity: 'uncommon',
    effectType: 'buff_def',
    effectValue: 15,
    effectDuration: 3,
    flavorText: 'So tight they double as a blood pressure test.',
  },
  lifting_belt: {
    itemKey: 'lifting_belt',
    name: 'Lifting Belt',
    description: 'Boosts ATK by 18 for 2 turns.',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 18,
    effectDuration: 2,
    flavorText: 'Cinch it tight enough and your face turns purple. That means it\'s working.',
  },
  ice_bath: {
    itemKey: 'ice_bath',
    name: 'Ice Bath',
    description: 'Restores 35 HP. Pain is temporary, gains are forever.',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 35,
    flavorText: 'Nothing says "I love my body" like submerging it in ice water while screaming.',
  },
  massage_gun: {
    itemKey: 'massage_gun',
    name: 'Massage Gun',
    description: 'Restores 30 HP. BRRRRRRR.',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 30,
    flavorText: 'Sounds like a power drill, feels like heaven, costs like a car payment.',
  },
  creatine_scoop: {
    itemKey: 'creatine_scoop',
    name: 'Creatine Scoop',
    description: 'Boosts ATK by 12 for 3 turns.',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 12,
    effectDuration: 3,
    flavorText: 'The only legal performance enhancer. Load phase = bloat phase.',
  },
  smelling_salts: {
    itemKey: 'smelling_salts',
    name: 'Smelling Salts',
    description: 'Boosts SPD by 20 for 1 turn. Instant adrenaline.',
    rarity: 'uncommon',
    effectType: 'buff_spd',
    effectValue: 20,
    effectDuration: 1,
    flavorText: 'Powerlifters swear by it. Your nose will never forgive you.',
  },
  battle_rope: {
    itemKey: 'battle_rope',
    name: 'Battle Rope',
    description: 'Deals 25 direct damage. Whip it good.',
    rarity: 'uncommon',
    effectType: 'direct_damage',
    effectValue: 25,
    flavorText: 'Making waves has never been this exhausting or this violent.',
  },
  weight_plate: {
    itemKey: 'weight_plate',
    name: 'Weight Plate',
    description: 'Deals 22 direct damage. 45 lbs of justice.',
    rarity: 'uncommon',
    effectType: 'direct_damage',
    effectValue: 22,
    flavorText: 'A frisbee for people who hate fun and love gains.',
  },
  gym_chalk_block: {
    itemKey: 'gym_chalk_block',
    name: 'Gym Chalk Block',
    description: 'Reduces opponent ATK by 12 for 2 turns.',
    rarity: 'uncommon',
    effectType: 'debuff_atk',
    effectValue: 12,
    effectDuration: 2,
    flavorText: 'Throw it in their eyes. Chalk cloud of confusion.',
  },
  bcaa_mix: {
    itemKey: 'bcaa_mix',
    name: 'BCAA Mix',
    description: 'Restores 25 HP. Branch chain amino acids, bro.',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 25,
    flavorText: 'Tastes like a melted gummy bear. Probably does nothing. But MAYBE it does everything.',
  },

  gps_watch: {
    itemKey: 'gps_watch',
    name: 'GPS Watch',
    description: 'Boosts SPD by 18 for 2 turns. Data is power.',
    rarity: 'uncommon',
    effectType: 'buff_spd',
    effectValue: 18,
    effectDuration: 2,
    flavorText: 'Costs $400. Battery dies at mile 24 of your marathon. Every time.',
  },
  clipless_pedals: {
    itemKey: 'clipless_pedals',
    name: 'Clipless Pedals',
    description: 'Boosts ATK by 15 for 2 turns. Locked in and lethal.',
    rarity: 'uncommon',
    effectType: 'buff_atk',
    effectValue: 15,
    effectDuration: 2,
    flavorText: 'Called "clipless" but you clip into them. Cycling naming conventions are chaos.',
  },
  racing_flats: {
    itemKey: 'racing_flats',
    name: 'Racing Flats',
    description: 'Boosts SPD by 22 for 1 turn. Carbon-plated speed.',
    rarity: 'uncommon',
    effectType: 'buff_spd',
    effectValue: 22,
    effectDuration: 1,
    flavorText: 'Super shoes that cost more per mile than your car. Worth every penny on race day.',
  },
  recovery_shake: {
    itemKey: 'recovery_shake',
    name: 'Recovery Shake',
    description: 'Restores 30 HP. Chocolate milk\'s fancy cousin.',
    rarity: 'uncommon',
    effectType: 'heal',
    effectValue: 30,
    flavorText: 'Science says chocolate milk works just as well. But this has a better label.',
  },
  wind_resistance_spray: {
    itemKey: 'wind_resistance_spray',
    name: 'Aero Spray',
    description: 'Reduces opponent DEF by 15 for 2 turns. Slice through the wind.',
    rarity: 'uncommon',
    effectType: 'debuff_def',
    effectValue: 15,
    effectDuration: 2,
    flavorText: 'Makes you 0.3% more aerodynamic. Cyclists will pay anything for 0.3%.',
  },

  // === RARE (7) ===
  golden_dumbbell: {
    itemKey: 'golden_dumbbell',
    name: 'Golden Dumbbell',
    description: 'Boosts ATK by 25 for 3 turns. Pure gold, pure gains.',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 25,
    effectDuration: 3,
    flavorText: 'Forged in the fires of a thousand failed New Year\'s resolutions.',
  },
  unlimited_gym_pass: {
    itemKey: 'unlimited_gym_pass',
    name: 'Unlimited Gym Pass',
    description: 'Restores 50 HP. All-access recovery.',
    rarity: 'rare',
    effectType: 'heal',
    effectValue: 50,
    flavorText: 'The mythical pass that never expires. They said it couldn\'t exist.',
  },
  personal_trainer: {
    itemKey: 'personal_trainer',
    name: 'Personal Trainer',
    description: 'Boosts ATK by 20 and DEF by 15 for 3 turns.',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 20,
    effectDuration: 3,
    flavorText: 'Costs more per hour than a lawyer. Worth it for the "one more rep" motivation.',
  },
  titanium_barbell: {
    itemKey: 'titanium_barbell',
    name: 'Titanium Barbell',
    description: 'Deals 40 direct damage. Indestructible iron.',
    rarity: 'rare',
    effectType: 'direct_damage',
    effectValue: 40,
    flavorText: 'They said it was unbreakable. Your opponent wishes it wasn\'t.',
  },
  olympic_rings: {
    itemKey: 'olympic_rings',
    name: 'Olympic Rings',
    description: 'Boosts all stats by 15 for 2 turns.',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 15,
    effectDuration: 2,
    flavorText: 'Channel the spirit of every athlete who ever said "I trained my whole life for this."',
  },
  dragon_flag_cape: {
    itemKey: 'dragon_flag_cape',
    name: 'Dragon Flag Cape',
    description: 'Boosts DEF by 25 for 3 turns. Core of steel.',
    rarity: 'rare',
    effectType: 'buff_def',
    effectValue: 25,
    effectDuration: 3,
    flavorText: 'Only Bruce Lee could do it. You pretend you can. The cape doesn\'t judge.',
  },
  elixir_of_gains: {
    itemKey: 'elixir_of_gains',
    name: 'Elixir of Gains',
    description: 'Restores 60 HP. The ultimate recovery potion.',
    rarity: 'rare',
    effectType: 'heal',
    effectValue: 60,
    flavorText: 'Ingredients: whey protein, creatine, belief, and a dash of pre-workout. Shake vigorously.',
  },
  marathon_medal: {
    itemKey: 'marathon_medal',
    name: 'Marathon Medal',
    description: 'Boosts SPD by 25 for 3 turns. 26.2 miles of glory.',
    rarity: 'rare',
    effectType: 'buff_spd',
    effectValue: 25,
    effectDuration: 3,
    flavorText: 'You ran 42km for a $3 medal and a space blanket. And you\'d do it again.',
  },
  carbon_fiber_frame: {
    itemKey: 'carbon_fiber_frame',
    name: 'Carbon Fiber Frame',
    description: 'Deals 35 direct damage. Lighter than air, harder than steel.',
    rarity: 'rare',
    effectType: 'direct_damage',
    effectValue: 35,
    flavorText: 'This bike frame costs more than most cars. Don\'t lean it against anything.',
  },
  finisher_tape: {
    itemKey: 'finisher_tape',
    name: 'Finisher Tape',
    description: 'Boosts ATK by 22 for 3 turns. Cross the line first.',
    rarity: 'rare',
    effectType: 'buff_atk',
    effectValue: 22,
    effectDuration: 3,
    flavorText: 'That moment when you break the tape and everything was worth it.',
  },
}
