import type { ShopItem } from '../types'

export const exerciseShopCatalog: ShopItem[] = [
  // === MERCH (6, unavailable) ===
  {
    slug: 'golden-dumbbell-trophy',
    name: 'Golden Dumbbell Trophy',
    description: 'A miniature golden dumbbell on a marble base. For your desk, your shelf, or your ego.',
    price: 500,
    category: 'merch',
    flavorText: 'Finally, a trophy for showing up. Participation gains.',
    available: false,
  },
  {
    slug: 'finisher-medal-display',
    name: 'Finisher Medal Display',
    description: 'A velvet-lined frame to display your race medals. Empty frames accepted.',
    price: 450,
    category: 'merch',
    flavorText: 'For the runner who needs everyone to know about that one 5K in 2019.',
    available: false,
  },
  {
    slug: 'mystery-supplement-plushie',
    name: 'Mystery Supplement Plushie',
    description: 'A soft, huggable tub of mystery powder. What flavor is it? Nobody knows.',
    price: 250,
    category: 'merch',
    flavorText: 'Squeeze it and it makes a shaker bottle sound. Terrifying.',
    available: false,
  },
  {
    slug: 'strava-crown-pin',
    name: 'Strava Crown Pin',
    description: 'A golden crown pin for the segment hunter in your life. Enamel, shiny, obnoxious.',
    price: 200,
    category: 'merch',
    flavorText: 'Wear it on your jersey so everyone knows you KOM\'d that one flat segment at 3am.',
    available: false,
  },
  {
    slug: 'survived-leg-day-tee',
    name: '"I Survived Leg Day" T-Shirt',
    description: 'Battle-worn aesthetic. Comes pre-wrinkled to simulate post-workout collapse.',
    price: 300,
    category: 'merch',
    flavorText: 'The stairs were the real boss fight.',
    available: false,
  },
  {
    slug: 'dns-dnf-cap',
    name: '"DNS > DNF > DFL" Cap',
    description: 'A trucker cap with the runner\'s hierarchy of shame. Adjustable fit.',
    price: 280,
    category: 'merch',
    flavorText: 'Did Not Start beats Did Not Finish beats Dead Last. But showing up beats all three.',
    available: false,
  },

  // === CARD PACKS (3) ===
  {
    slug: 'budget-bro-pack',
    name: 'Budget Banger Pack',
    description: '1 random card. Lower your expectations accordingly.',
    price: 100,
    category: 'card_pack',
    flavorText: 'Scraped together from the clearance bin at the card factory. May or may not be slightly damp.',
    available: true,
    rewardCount: 1,
    rewardRarity: 'common',
  },
  {
    slug: 'coachs-selection',
    name: 'Coach\'s Selection',
    description: '3 random cards, at least 1 guaranteed uncommon or better.',
    price: 500,
    category: 'card_pack',
    flavorText: 'Hand-picked by a coach with 40 years of experience. These cards have seen things.',
    available: true,
    rewardCount: 3,
    rewardRarity: 'uncommon',
  },
  {
    slug: 'forbidden-locker',
    name: 'The Forbidden Crate',
    description: '5 random cards with 1 guaranteed rare. Handle with oven mitts.',
    price: 2000,
    category: 'card_pack',
    flavorText: 'Found in the back of an abandoned meat locker. Glows faintly when exposed to moonlight.',
    available: true,
    rewardCount: 5,
    rewardRarity: 'rare',
  },

  // === ITEMS (4) ===
  {
    slug: 'mystery-supplement',
    name: 'Mystery Supplement',
    description: '1 random battle item. Could be energy gel, could be chalk.',
    price: 75,
    category: 'item',
    flavorText: 'The label fell off. Just take it and trust the process.',
    available: true,
    rewardCount: 1,
    rewardRarity: 'mixed',
  },
  {
    slug: 'premium-pre-workout',
    name: 'Premium Fuel Pack',
    description: '2 random items, uncommon or better. Gels, watches, shoes — who knows.',
    price: 200,
    category: 'item',
    flavorText: 'The good stuff from the back of the pro shop.',
    available: true,
    rewardCount: 2,
    rewardRarity: 'uncommon',
  },
  {
    slug: 'coachs-secret-stash',
    name: 'Coach\'s Secret Stash',
    description: '2 rare items from coach\'s personal collection.',
    price: 400,
    category: 'item',
    flavorText: 'Coach keeps these locked in a safe behind the squat rack. Don\'t ask questions.',
    available: true,
    rewardCount: 2,
    rewardRarity: 'rare',
  },
  {
    slug: 'bulk-protein-crate',
    name: 'Bulk Gear Crate',
    description: '5 random items across all rarities. Maximum haul.',
    price: 350,
    category: 'item',
    flavorText: 'Delivered in a wooden crate with "GAINS INSIDE" stamped on it.',
    available: true,
    rewardCount: 5,
    rewardRarity: 'mixed',
  },
]
