import type { ShopItem } from '../types'

export const exerciseShopCatalog: ShopItem[] = [
  // === MERCH (6, unavailable) ===
  {
    slug: 'golden-dumbbell-trophy',
    name: 'Golden Dumbbell Trophy',
    description: 'A miniature golden dumbbell on a marble base. For your desk, your shelf, or your ego.',
    price: 500,
    category: 'merch',
    flavorText: 'Finally, a trophy for showing up. Participation gains.',
    available: false,
  },
  {
    slug: 'never-skip-leg-day-tank',
    name: '"I Never Skip Leg Day" Tank Top',
    description: 'Premium cotton tank. The lie detector test determined that was a lie.',
    price: 350,
    category: 'merch',
    flavorText: 'Wearing this tank top does not count as evidence of leg training.',
    available: false,
  },
  {
    slug: 'mystery-supplement-plushie',
    name: 'Mystery Supplement Plushie',
    description: 'A soft, huggable tub of mystery powder. What flavor is it? Nobody knows.',
    price: 250,
    category: 'merch',
    flavorText: 'Squeeze it and it makes a shaker bottle sound. Terrifying.',
    available: false,
  },
  {
    slug: 'commemorative-lifting-belt',
    name: 'Commemorative Lifting Belt',
    description: 'A real leather lifting belt with your username embossed on it. Not for actual lifting.',
    price: 600,
    category: 'merch',
    flavorText: 'Disclaimer: wearing this belt does not add 50 lbs to your squat.',
    available: false,
  },
  {
    slug: 'survived-leg-day-tee',
    name: '"I Survived Leg Day" T-Shirt',
    description: 'Battle-worn aesthetic. Comes pre-wrinkled to simulate post-workout collapse.',
    price: 300,
    category: 'merch',
    flavorText: 'The stairs were the real boss fight.',
    available: false,
  },
  {
    slug: 'usb-protein-shaker',
    name: 'USB Desktop Protein Shaker',
    description: 'A tiny motorized shaker bottle for your desk. Mixes protein shakes via USB power.',
    price: 400,
    category: 'merch',
    flavorText: 'Finally, you can mix your afternoon shake without leaving your gaming chair.',
    available: false,
  },

  // === CARD PACKS (3) ===
  {
    slug: 'budget-bro-pack',
    name: 'Budget Bro Pack',
    description: '3 random cards. Mostly common, like your gym routine.',
    price: 100,
    category: 'card_pack',
    flavorText: 'You get what you pay for. Which is usually a Treadmill Walker variant.',
    available: true,
    rewardCount: 3,
    rewardRarity: 'common',
  },
  {
    slug: 'coachs-selection',
    name: 'Coach\'s Selection',
    description: '3 cards hand-picked by coach. Guaranteed uncommon or better.',
    price: 250,
    category: 'card_pack',
    flavorText: 'Coach knows best. Coach also charges extra. That\'s the coach way.',
    available: true,
    rewardCount: 3,
    rewardRarity: 'uncommon',
  },
  {
    slug: 'forbidden-locker',
    name: 'The Forbidden Locker',
    description: '3 premium cards from the locker nobody dares open. Guaranteed rare.',
    price: 500,
    category: 'card_pack',
    flavorText: 'That locker in the corner that\'s been locked since 1987. What\'s inside? GAINS.',
    available: true,
    rewardCount: 3,
    rewardRarity: 'rare',
  },

  // === ITEMS (4) ===
  {
    slug: 'mystery-supplement',
    name: 'Mystery Supplement',
    description: '1 random battle item. Could be anything. Probably creatine.',
    price: 75,
    category: 'item',
    flavorText: 'The label fell off. Just take it and trust the process.',
    available: true,
    rewardCount: 1,
    rewardRarity: 'mixed',
  },
  {
    slug: 'premium-pre-workout',
    name: 'Premium Pre-Workout',
    description: '2 random items, uncommon or better. Feel the tingle.',
    price: 200,
    category: 'item',
    flavorText: 'Beta-alanine face tingles are a feature, not a bug.',
    available: true,
    rewardCount: 2,
    rewardRarity: 'uncommon',
  },
  {
    slug: 'coachs-secret-stash',
    name: 'Coach\'s Secret Stash',
    description: '2 rare items from coach\'s personal collection.',
    price: 400,
    category: 'item',
    flavorText: 'Coach keeps these locked in a safe behind the squat rack. Don\'t ask questions.',
    available: true,
    rewardCount: 2,
    rewardRarity: 'rare',
  },
  {
    slug: 'bulk-protein-crate',
    name: 'Bulk Protein Crate',
    description: '5 random items across all rarities. Maximum supplement haul.',
    price: 350,
    category: 'item',
    flavorText: 'Delivered in a wooden crate with "GAINS INSIDE" stamped on it.',
    available: true,
    rewardCount: 5,
    rewardRarity: 'mixed',
  },
]
