import type { StarterCard } from '../types'

export const exerciseStarters: StarterCard[] = [
  {
    heroTitle: 'Couch Potato Carl',
    heroType: 'CARDIO/FLEXIBILITY',
    hp: 85,
    attack: 30,
    defense: 45,
    speed: 20,
    specialMoves: [
      'Remote Reach (20/8)',
      'Lazy Stretch (25/6)',
      'Channel Surf Cardio (35/4)',
    ],
    weakness: 'Gets winded walking to the fridge',
    catchphrase: 'I\'ll start Monday... next Monday.',
    flavorText: 'Legend says Carl once held a plank for 3 seconds. He talks about it constantly. His idea of cardio is running late.',
    weekKey: 'STARTER-1',
  },
  {
    heroTitle: 'Skip Leg Day Steve',
    heroType: 'STRENGTH/SPEED',
    hp: 90,
    attack: 55,
    defense: 25,
    speed: 35,
    specialMoves: [
      'Bicep Curl Fury (40/5)',
      'Mirror Flex (15/8)',
      'Top-Heavy Topple (55/3)',
    ],
    weakness: 'A strong breeze could knock him over',
    catchphrase: 'Legs? Never heard of \'em.',
    flavorText: 'Steve\'s upper body is a fortress. His legs are pool noodles. He wears pants year-round for a reason.',
    weekKey: 'STARTER-2',
  },
  {
    heroTitle: 'New Year\'s Resolution',
    heroType: 'HIIT/YOGA',
    hp: 95,
    attack: 50,
    defense: 30,
    speed: 40,
    specialMoves: [
      'January Burst (50/3)',
      'Motivation Fade (20/7)',
      'February Quit (30/5)',
    ],
    weakness: 'Loses all power after January 15th',
    catchphrase: 'THIS is the year! (for the 5th time)',
    flavorText: 'Arrives January 1st with brand new gear and a 12-month plan. Cancels gym membership by Valentine\'s Day.',
    weekKey: 'STARTER-3',
  },
  {
    heroTitle: 'The Treadmill Walker',
    heroType: 'CARDIO/ENDURANCE',
    hp: 100,
    attack: 25,
    defense: 40,
    speed: 15,
    specialMoves: [
      'Leisurely Stroll (15/8)',
      'Incline 0.5 (25/6)',
      'Phone Scroll Sprint (35/4)',
    ],
    weakness: 'Has never touched the speed button',
    catchphrase: '2.0 mph is a lifestyle, not a speed.',
    flavorText: 'Has been on the treadmill for 45 minutes at walking pace while binge-watching Netflix. Counts it as a marathon.',
    weekKey: 'STARTER-4',
  },
  {
    heroTitle: 'Foam Roller Fred',
    heroType: 'FLEXIBILITY/CALISTHENICS',
    hp: 110,
    attack: 20,
    defense: 55,
    speed: 25,
    specialMoves: [
      'Deep Tissue Roll (20/7)',
      'Trigger Point Poke (30/5)',
      'Recovery Day Block (10/8)',
    ],
    weakness: 'Spends the entire gym session "warming up"',
    catchphrase: 'Recovery IS the workout, bro.',
    flavorText: 'Fred\'s entire gym routine is foam rolling, stretching, and telling people about the importance of mobility. Has never lifted a weight.',
    weekKey: 'STARTER-5',
  },
]
