import type { StarterCard } from '../types'

export const exerciseStarters: StarterCard[] = [
  {
    heroTitle: 'Couch Potato Carl',
    heroType: 'CARDIO/FLEXIBILITY',
    hp: 85, attack: 30, defense: 45, speed: 20,
    specialMoves: ['Remote Reach (20/8)', 'Lazy Stretch (25/6)', 'Channel Surf Cardio (35/4)'],
    weakness: 'Gets winded walking to the fridge',
    catchphrase: 'I\'ll start Monday... next Monday.',
    flavorText: 'Legend says Carl once held a plank for 3 seconds. He talks about it constantly.',
    weekKey: 'STARTER-1',
  },
  {
    heroTitle: 'Skip Leg Day Steve',
    heroType: 'STRENGTH/SPEED',
    hp: 90, attack: 55, defense: 25, speed: 35,
    specialMoves: ['Bicep Curl Fury (40/5)', 'Mirror Flex (15/8)', 'Top-Heavy Topple (55/3)'],
    weakness: 'A strong breeze could knock him over',
    catchphrase: 'Legs? Never heard of \'em.',
    flavorText: 'Steve\'s upper body is a fortress. His legs are pool noodles. He wears pants year-round.',
    weekKey: 'STARTER-2',
  },
  {
    heroTitle: 'New Year\'s Resolution',
    heroType: 'HIIT/YOGA',
    hp: 95, attack: 50, defense: 30, speed: 40,
    specialMoves: ['January Burst (50/3)', 'Motivation Fade (20/7)', 'February Quit (30/5)'],
    weakness: 'Loses all power after January 15th',
    catchphrase: 'THIS is the year! (for the 5th time)',
    flavorText: 'Arrives January 1st with brand new gear. Cancels membership by Valentine\'s Day.',
    weekKey: 'STARTER-3',
  },
  {
    heroTitle: 'The Treadmill Walker',
    heroType: 'CARDIO/ENDURANCE',
    hp: 100, attack: 25, defense: 40, speed: 15,
    specialMoves: ['Leisurely Stroll (15/8)', 'Incline 0.5 (25/6)', 'Phone Scroll Sprint (35/4)'],
    weakness: 'Has never touched the speed button',
    catchphrase: '2.0 mph is a lifestyle, not a speed.',
    flavorText: 'Has been on the treadmill for 45 minutes at walking pace while watching Netflix.',
    weekKey: 'STARTER-4',
  },
  {
    heroTitle: 'Foam Roller Fred',
    heroType: 'FLEXIBILITY/CALISTHENICS',
    hp: 110, attack: 20, defense: 55, speed: 25,
    specialMoves: ['Deep Tissue Roll (20/7)', 'Trigger Point Poke (30/5)', 'Recovery Day Block (10/8)'],
    weakness: 'Spends the entire gym session "warming up"',
    catchphrase: 'Recovery IS the workout, bro.',
    flavorText: 'Fred\'s entire routine is foam rolling and telling people about mobility.',
    weekKey: 'STARTER-5',
  },
  {
    heroTitle: 'Selfie Samantha',
    heroType: 'YOGA/SPEED',
    hp: 80, attack: 35, defense: 30, speed: 50,
    specialMoves: ['Angle Adjust (15/8)', 'Filter Blast (40/4)', 'Story Upload Surge (30/6)'],
    weakness: 'Bad lighting drains all HP',
    catchphrase: 'Did the workout even happen if nobody saw it?',
    flavorText: 'Spends 40 minutes finding the perfect gym selfie angle, 5 minutes working out.',
    weekKey: 'STARTER-6',
  },
  {
    heroTitle: 'Protein Shake Pete',
    heroType: 'STRENGTH/ENDURANCE',
    hp: 105, attack: 45, defense: 35, speed: 20,
    specialMoves: ['Whey Toss (35/5)', 'Creatine Charge (45/4)', 'Mass Gainer Slam (55/3)'],
    weakness: 'Useless if blender is broken',
    catchphrase: 'I need 200g of protein MINIMUM.',
    flavorText: 'Pete carries a shaker bottle everywhere. Has tried every flavor. His kitchen is 90% tubs.',
    weekKey: 'STARTER-7',
  },
  {
    heroTitle: 'Cardio Bunny Bri',
    heroType: 'CARDIO/SPEED',
    hp: 75, attack: 30, defense: 20, speed: 60,
    specialMoves: ['Elliptical Escape (25/7)', 'Stairmaster Sprint (40/4)', 'Spin Class Cyclone (50/3)'],
    weakness: 'Panics near the free weights',
    catchphrase: 'I just do cardio, it\'s simpler.',
    flavorText: 'Has done 3 hours of cardio but has never touched a barbell. The weight room is "scary."',
    weekKey: 'STARTER-8',
  },
  {
    heroTitle: 'Gym Bro Chad',
    heroType: 'STRENGTH/POWER',
    hp: 95, attack: 55, defense: 30, speed: 25,
    specialMoves: ['Unsolicited Advice (30/6)', 'Bro Split Bash (45/4)', 'Ego Lift (60/2)'],
    weakness: 'Cannot resist giving unwanted tips',
    catchphrase: 'Nah bro, you\'re doing it wrong. Let me show you.',
    flavorText: 'Chad has been doing the same bro split for 6 years. It\'s his personality now.',
    weekKey: 'STARTER-9',
  },
  {
    heroTitle: 'The Machine Hogger',
    heroType: 'STRENGTH/ENDURANCE',
    hp: 115, attack: 35, defense: 50, speed: 10,
    specialMoves: ['Occupy Bench (10/8)', 'Superset Lockdown (30/5)', 'Rest Period Extend (20/7)'],
    weakness: 'Crumbles when someone asks to work in',
    catchphrase: 'I\'ve got 12 more sets.',
    flavorText: 'Has been on the same machine for 45 minutes. Half of that was scrolling Instagram.',
    weekKey: 'STARTER-10',
  },
  {
    heroTitle: 'Yoga Mat Yuki',
    heroType: 'YOGA/FLEXIBILITY',
    hp: 90, attack: 25, defense: 50, speed: 35,
    specialMoves: ['Downward Dog Drop (25/6)', 'Namaste Shield (15/8)', 'Warrior III Strike (40/4)'],
    weakness: 'Loses balance during Tree Pose',
    catchphrase: 'Breathe in the gains, breathe out the toxins.',
    flavorText: 'Yuki\'s flexibility is legendary. Has fallen asleep in Shavasana more than once.',
    weekKey: 'STARTER-11',
  },
  {
    heroTitle: 'CrossFit Kyle',
    heroType: 'CROSSFIT/POWER',
    hp: 85, attack: 50, defense: 25, speed: 45,
    specialMoves: ['Kipping Chaos (45/4)', 'WOD Blitz (55/3)', 'Box Jump Bonk (30/6)'],
    weakness: 'Will tell you he does CrossFit within 30 seconds',
    catchphrase: 'You wouldn\'t understand, it\'s a CrossFit thing.',
    flavorText: 'Kyle\'s form is questionable but his intensity is unmatched. Owns 14 pairs of Nanos.',
    weekKey: 'STARTER-12',
  },
  {
    heroTitle: 'The Grunter',
    heroType: 'POWER/STRENGTH',
    hp: 100, attack: 60, defense: 30, speed: 15,
    specialMoves: ['Primal Scream (50/3)', 'Weight Slam (55/3)', 'Intimidation Roar (25/6)'],
    weakness: 'Gets kicked out of Planet Fitness',
    catchphrase: 'AAAARRRGGGHHHH! ...sorry.',
    flavorText: 'You can hear him from the parking lot. Every rep sounds like a wildlife documentary.',
    weekKey: 'STARTER-13',
  },
  {
    heroTitle: 'Rest Day Ronnie',
    heroType: 'FLEXIBILITY/ENDURANCE',
    hp: 120, attack: 15, defense: 55, speed: 10,
    specialMoves: ['Active Recovery (10/8)', 'Netflix Marathon (20/7)', 'Sleep In Shield (15/8)'],
    weakness: 'Every day is rest day',
    catchphrase: 'My body needs this. It\'s science.',
    flavorText: 'Ronnie hasn\'t been to the gym in 3 weeks but is "actively recovering." Very active.',
    weekKey: 'STARTER-14',
  },
  {
    heroTitle: 'The Personal Trainer',
    heroType: 'STRENGTH/HIIT',
    hp: 88, attack: 40, defense: 35, speed: 40,
    specialMoves: ['Free Session Hook (30/6)', 'Clipboard Command (40/5)', 'Upsell Ultimate (50/3)'],
    weakness: 'Powerless without a client to correct',
    catchphrase: 'First session is free! The next 50 aren\'t.',
    flavorText: 'Carries a clipboard, wears a polo. Will "fix your form" even if you didn\'t ask.',
    weekKey: 'STARTER-15',
  },
  {
    heroTitle: 'Smoothie Queen Sara',
    heroType: 'CARDIO/YOGA',
    hp: 80, attack: 30, defense: 35, speed: 45,
    specialMoves: ['Açaí Bowl Blast (35/5)', 'Matcha Missile (25/7)', 'Green Juice Gush (45/4)'],
    weakness: 'If Whole Foods closes, she\'s done',
    catchphrase: 'It\'s not a meal, it\'s a lifestyle.',
    flavorText: 'Sara\'s post-workout smoothie costs more than the gym membership.',
    weekKey: 'STARTER-16',
  },
  {
    heroTitle: 'The Belt Wearer',
    heroType: 'POWER/STRENGTH',
    hp: 95, attack: 50, defense: 40, speed: 15,
    specialMoves: ['Belt Cinch (20/7)', 'Valsalva Burst (45/4)', 'Chalk Cloud (35/5)'],
    weakness: 'Wears a belt for everything including bicep curls',
    catchphrase: 'Safety first. Even on the elliptical.',
    flavorText: 'Bought a lifting belt for squats. Now wears it for literally every exercise.',
    weekKey: 'STARTER-17',
  },
  {
    heroTitle: 'HIIT Hannah',
    heroType: 'HIIT/SPEED',
    hp: 75, attack: 45, defense: 20, speed: 55,
    specialMoves: ['Burpee Barrage (50/3)', 'Mountain Climber Rush (35/5)', 'Tabata Terror (40/4)'],
    weakness: 'Completely gassed after 20 minutes',
    catchphrase: 'If you\'re not dying, you\'re not trying!',
    flavorText: 'Hannah\'s workouts last 20 minutes but feel like 3 hours. Puddle of sweat guaranteed.',
    weekKey: 'STARTER-18',
  },
  {
    heroTitle: 'Old School Hank',
    heroType: 'STRENGTH/ENDURANCE',
    hp: 110, attack: 45, defense: 45, speed: 10,
    specialMoves: ['Classic Deadlift (50/3)', 'Strict Press (35/5)', 'Wisdom Flex (20/7)'],
    weakness: 'Refuses to learn any exercise invented after 1985',
    catchphrase: 'Back in my day, we didn\'t need machines.',
    flavorText: 'Hank uses nothing but a barbell and judgment. Has trained since before you were born.',
    weekKey: 'STARTER-19',
  },
  {
    heroTitle: 'The Spotter',
    heroType: 'STRENGTH/FLEXIBILITY',
    hp: 100, attack: 30, defense: 45, speed: 30,
    specialMoves: ['Forced Rep (35/5)', 'Spot Steal (25/6)', 'All You Bro (40/4)'],
    weakness: 'Does more work spotting than lifting',
    catchphrase: 'It\'s ALL you! ...mostly.',
    flavorText: 'Has spot-lifted more total weight than he\'s ever actually pressed himself.',
    weekKey: 'STARTER-20',
  },
  {
    heroTitle: 'Wearable Tech Wendy',
    heroType: 'CARDIO/HIIT',
    hp: 80, attack: 35, defense: 30, speed: 45,
    specialMoves: ['Data Dump (30/6)', 'Heart Rate Alert (40/4)', 'Zone 2 Drain (25/7)'],
    weakness: 'Won\'t start until watch has GPS lock',
    catchphrase: 'My watch says I burned 800 calories!',
    flavorText: 'Has a $400 watch, $200 ring, and a chest strap. Can\'t do a push-up.',
    weekKey: 'STARTER-21',
  },
  {
    heroTitle: 'Deadlift Danny',
    heroType: 'POWER/STRENGTH',
    hp: 105, attack: 55, defense: 35, speed: 15,
    specialMoves: ['Sumo Slam (50/3)', 'Conventional Crush (45/4)', 'Chalk Storm (25/6)'],
    weakness: 'Only knows one exercise',
    catchphrase: 'Why bench when you can pull?',
    flavorText: 'Danny deadlifts on leg day, arm day, and cardio day. Everything is deadlift day.',
    weekKey: 'STARTER-22',
  },
  {
    heroTitle: 'The Influencer',
    heroType: 'YOGA/SPEED',
    hp: 70, attack: 40, defense: 25, speed: 50,
    specialMoves: ['Ring Light Blind (35/5)', 'Sponsored Post (45/4)', 'Follow for Follow (20/7)'],
    weakness: 'Falls apart without WiFi',
    catchphrase: 'Use code GAINS for 10% off!',
    flavorText: 'Workouts are content first, training second. Has 50K followers and a 95lb squat.',
    weekKey: 'STARTER-23',
  },
  {
    heroTitle: 'Sauna Sam',
    heroType: 'ENDURANCE/FLEXIBILITY',
    hp: 115, attack: 20, defense: 50, speed: 15,
    specialMoves: ['Heat Soak (15/8)', 'Cold Plunge Shock (40/4)', 'Contrast Therapy (30/5)'],
    weakness: 'Spends more time in sauna than lifting',
    catchphrase: 'The real gains happen in the heat.',
    flavorText: 'Sam goes to the gym exclusively for the sauna. Has a "routine" of sitting.',
    weekKey: 'STARTER-24',
  },
  {
    heroTitle: 'Calisthenics Chris',
    heroType: 'CALISTHENICS/SPEED',
    hp: 85, attack: 40, defense: 35, speed: 45,
    specialMoves: ['Muscle Up Mayhem (50/3)', 'Planche Push (35/5)', 'L-Sit Lightning (25/6)'],
    weakness: 'Refuses to touch a barbell on principle',
    catchphrase: 'I don\'t need weights, I AM the weight.',
    flavorText: 'Can do a human flag but can\'t bench his body weight. Considers this a flex.',
    weekKey: 'STARTER-25',
  },
  {
    heroTitle: 'Pre-Workout Patty',
    heroType: 'HIIT/POWER',
    hp: 80, attack: 55, defense: 20, speed: 50,
    specialMoves: ['Caffeine Rush (50/3)', 'Beta-Alanine Tingle (30/5)', 'Stim Overload (60/2)'],
    weakness: 'Crashes hard after 30 minutes',
    catchphrase: 'TWO scoops today. SEND IT.',
    flavorText: 'Takes enough pre-workout to power a small city. First 20 minutes are legendary.',
    weekKey: 'STARTER-26',
  },
  {
    heroTitle: 'The Stretcher',
    heroType: 'FLEXIBILITY/YOGA',
    hp: 100, attack: 20, defense: 50, speed: 30,
    specialMoves: ['Hamstring Hold (20/7)', 'Hip Opener (25/6)', 'Split Surprise (35/5)'],
    weakness: 'Stretches for so long the gym closes',
    catchphrase: 'You should really stretch more.',
    flavorText: 'Has been doing the splits in the stretching area for 90 minutes. Someone check on them.',
    weekKey: 'STARTER-27',
  },
  {
    heroTitle: 'Farmer\'s Walk Frank',
    heroType: 'STRENGTH/ENDURANCE',
    hp: 110, attack: 40, defense: 45, speed: 20,
    specialMoves: ['Grocery Grip (35/5)', 'Heavy Carry (45/4)', 'One Trip Wonder (55/3)'],
    weakness: 'Grip gives out at the worst times',
    catchphrase: 'Two trips is for the weak.',
    flavorText: 'Frank\'s entire training philosophy is carrying heavy things. Grocery day is PR day.',
    weekKey: 'STARTER-28',
  },
  {
    heroTitle: 'The Newbie',
    heroType: 'CARDIO/STRENGTH',
    hp: 90, attack: 30, defense: 30, speed: 30,
    specialMoves: ['Confused Wander (15/8)', 'YouTube Form Check (25/6)', 'Beginner Gains (45/4)'],
    weakness: 'Intimidated by everything',
    catchphrase: 'Is... is this how you use this?',
    flavorText: 'Just got a gym membership. Walks in, looks around, does 10 minutes on the bike, leaves.',
    weekKey: 'STARTER-29',
  },
  {
    heroTitle: 'Chalk Monster Mike',
    heroType: 'POWER/CALISTHENICS',
    hp: 95, attack: 50, defense: 30, speed: 25,
    specialMoves: ['Chalk Cloud (30/6)', 'Grip Rip (45/4)', 'White Hand Slap (35/5)'],
    weakness: 'Leaves chalk on everything including the water fountain',
    catchphrase: 'You can never have too much chalk.',
    flavorText: 'Mike uses more chalk than a primary school. The floor around him is a winter wonderland.',
    weekKey: 'STARTER-30',
  },
  {
    heroTitle: 'Spin Class Sally',
    heroType: 'CYCLING/CARDIO',
    hp: 80, attack: 35, defense: 25, speed: 55,
    specialMoves: ['Resistance Crank (40/4)', 'Standing Climb (30/6)', 'Sprint Finish (50/3)'],
    weakness: 'Completely lost outside of spin class',
    catchphrase: 'FEEL THE RHYTHM! TURN IT UP!',
    flavorText: 'Sally has done 500 spin classes. Still can\'t change a bike tire.',
    weekKey: 'STARTER-31',
  },
  {
    heroTitle: 'The Circuit Trainer',
    heroType: 'HIIT/ENDURANCE',
    hp: 85, attack: 40, defense: 35, speed: 40,
    specialMoves: ['Station Hop (30/6)', 'No Rest Round (45/4)', 'Timer Beep Blast (35/5)'],
    weakness: 'Takes up 6 machines at once during peak hours',
    catchphrase: 'DON\'T TOUCH THAT, I\'M USING IT!',
    flavorText: 'Has claimed half the gym for a "circuit." Put a towel on each machine like a German at a pool.',
    weekKey: 'STARTER-32',
  },
  {
    heroTitle: 'The Mirror Flexer',
    heroType: 'STRENGTH/YOGA',
    hp: 80, attack: 35, defense: 30, speed: 40,
    specialMoves: ['Double Bi Pose (25/6)', 'Lat Spread (35/5)', 'Vacuum Flex (40/4)'],
    weakness: 'Performs poorly if no mirrors present',
    catchphrase: 'Not admiring myself, just checking form...',
    flavorText: 'Spends 60% of gym time in front of the mirror. The other 40% is finding the best mirror.',
    weekKey: 'STARTER-33',
  },
  {
    heroTitle: 'Barefoot Brian',
    heroType: 'CALISTHENICS/FLEXIBILITY',
    hp: 95, attack: 35, defense: 40, speed: 30,
    specialMoves: ['Toe Grip (25/6)', 'Natural Stride (30/5)', 'Ground Feel (20/7)'],
    weakness: 'Steps on a dumbbell and it\'s all over',
    catchphrase: 'Shoes are a prison for your feet.',
    flavorText: 'Brian trains barefoot because "it\'s how humans are meant to move." Staff hates him.',
    weekKey: 'STARTER-34',
  },
  {
    heroTitle: 'The Water Jug',
    heroType: 'ENDURANCE/STRENGTH',
    hp: 105, attack: 30, defense: 45, speed: 20,
    specialMoves: ['Hydration Heal (15/8)', 'Gallon Swing (35/5)', 'Water Weight (40/4)'],
    weakness: 'Bathroom breaks every 10 minutes',
    catchphrase: 'Stay hydrated or stay home.',
    flavorText: 'Carries a gallon jug everywhere. Has a "hydration schedule." Judges your water bottle.',
    weekKey: 'STARTER-35',
  },
  {
    heroTitle: 'Loud Music Lisa',
    heroType: 'POWER/HIIT',
    hp: 80, attack: 50, defense: 25, speed: 40,
    specialMoves: ['Bass Drop Slam (45/4)', 'Earbud Entangle (25/6)', 'Playlist Power (35/5)'],
    weakness: 'Phone dies = workout dies',
    catchphrase: 'I can\'t hear you, and I don\'t want to.',
    flavorText: 'Lisa\'s headphones are so loud you can hear her playlist from across the gym.',
    weekKey: 'STARTER-36',
  },
  {
    heroTitle: 'Smith Machine Stan',
    heroType: 'STRENGTH/ENDURANCE',
    hp: 110, attack: 40, defense: 45, speed: 10,
    specialMoves: ['Guided Press (35/5)', 'Fixed Path Fury (40/4)', 'Safety Catch (20/7)'],
    weakness: 'Completely helpless with a free barbell',
    catchphrase: 'It\'s basically the same thing.',
    flavorText: 'Stan does everything on the Smith machine. Bench, squats, rows, curls. Everything.',
    weekKey: 'STARTER-37',
  },
  {
    heroTitle: 'Jump Rope Jenny',
    heroType: 'SPEED/CARDIO',
    hp: 75, attack: 35, defense: 25, speed: 60,
    specialMoves: ['Double Under Doom (45/4)', 'Criss Cross (30/6)', 'Speed Skip (25/7)'],
    weakness: 'Trips on the rope at the worst moments',
    catchphrase: 'Boxers do it, so it must be elite.',
    flavorText: 'Jenny whips that rope so fast it creates a force field. Trips every 47th rep though.',
    weekKey: 'STARTER-38',
  },
  {
    heroTitle: 'The Meal Prepper',
    heroType: 'ENDURANCE/STRENGTH',
    hp: 100, attack: 35, defense: 40, speed: 25,
    specialMoves: ['Tupperware Toss (30/6)', 'Macro Count (20/7)', 'Chicken Breast Bomb (45/4)'],
    weakness: 'Eating out at a restaurant causes panic',
    catchphrase: 'I can\'t, it doesn\'t fit my macros.',
    flavorText: 'Has 14 identical containers of rice, chicken, and broccoli. Every. Single. Week.',
    weekKey: 'STARTER-39',
  },
  {
    heroTitle: 'Battle Rope Ricky',
    heroType: 'POWER/CARDIO',
    hp: 85, attack: 45, defense: 30, speed: 35,
    specialMoves: ['Alternating Wave (35/5)', 'Slam Storm (50/3)', 'Rope Tornado (40/4)'],
    weakness: 'Arms give out in 30 seconds',
    catchphrase: 'FEEL THE BURN! *dies after 20 seconds*',
    flavorText: 'Ricky attacks those ropes like they owe him money. Collapses shortly after.',
    weekKey: 'STARTER-40',
  },
  {
    heroTitle: 'The Supersets Guy',
    heroType: 'HIIT/STRENGTH',
    hp: 90, attack: 45, defense: 30, speed: 35,
    specialMoves: ['Double Exercise (40/4)', 'No Rest Blast (50/3)', 'Triple Threat (55/2)'],
    weakness: 'Never fully recovers between sets',
    catchphrase: 'Why do one exercise when you can do three?',
    flavorText: 'Does a bench press, then pushups, then flyes, then wonders why he\'s dizzy.',
    weekKey: 'STARTER-41',
  },
  {
    heroTitle: 'The Sweatband',
    heroType: 'CARDIO/ENDURANCE',
    hp: 95, attack: 30, defense: 40, speed: 30,
    specialMoves: ['Sweat Splash (25/6)', 'Retro Headband Boost (30/5)', 'Towel Whip (35/5)'],
    weakness: 'Dehydrates at an alarming rate',
    catchphrase: 'Sweating is fat crying. I must be very sad.',
    flavorText: 'Wears a headband, wristbands, and a towel. Looks like an 80s workout video extra.',
    weekKey: 'STARTER-42',
  },
  {
    heroTitle: 'Kettlebell Karen',
    heroType: 'POWER/HIIT',
    hp: 85, attack: 50, defense: 30, speed: 35,
    specialMoves: ['Turkish Get-Up (45/4)', 'Swing Storm (35/5)', 'Goblet Smash (50/3)'],
    weakness: 'Will argue that kettlebells are superior to everything',
    catchphrase: 'You don\'t need barbells if you have kettlebells.',
    flavorText: 'Karen has replaced every exercise with a kettlebell variation. Even cardio.',
    weekKey: 'STARTER-43',
  },
  {
    heroTitle: 'The Gum Chewer',
    heroType: 'SPEED/STRENGTH',
    hp: 80, attack: 40, defense: 30, speed: 45,
    specialMoves: ['Jaw Flex (20/7)', 'Bubble Pop (30/6)', 'Minty Fresh Rush (40/4)'],
    weakness: 'Accidentally swallows gum during heavy lifts',
    catchphrase: '*aggressive chewing intensifies*',
    flavorText: 'Chews gum like their life depends on it. Goes through a pack per workout.',
    weekKey: 'STARTER-44',
  },
  {
    heroTitle: 'Resistance Band Rita',
    heroType: 'FLEXIBILITY/STRENGTH',
    hp: 90, attack: 30, defense: 45, speed: 35,
    specialMoves: ['Band Snap (35/5)', 'Elastic Stretch (25/6)', 'Banded Walk (20/7)'],
    weakness: 'Band breaks at the worst possible moment',
    catchphrase: 'These are all you need. Seriously.',
    flavorText: 'Rita travels with 17 bands of different resistances. Has never touched a dumbbell.',
    weekKey: 'STARTER-45',
  },
  {
    heroTitle: 'The Plank Holder',
    heroType: 'CALISTHENICS/ENDURANCE',
    hp: 120, attack: 15, defense: 55, speed: 10,
    specialMoves: ['Infinite Hold (10/8)', 'Side Plank Shift (25/6)', 'Plank Stare (15/8)'],
    weakness: 'Can only do one exercise',
    catchphrase: 'I\'m at 4 minutes. Don\'t talk to me.',
    flavorText: 'Has been planking for an uncomfortable amount of time. Makes eye contact with everyone.',
    weekKey: 'STARTER-46',
  },
  {
    heroTitle: 'The Vlogger',
    heroType: 'SPEED/YOGA',
    hp: 75, attack: 35, defense: 25, speed: 50,
    specialMoves: ['Tripod Trip (30/6)', 'Thumbnail Punch (40/4)', 'Algorithm Boost (25/7)'],
    weakness: 'Stops mid-set to check camera angle',
    catchphrase: 'Hey guys, welcome back to my channel!',
    flavorText: 'Sets up a camera, ring light, and mic before doing 3 sets of nothing impressive.',
    weekKey: 'STARTER-47',
  },
  {
    heroTitle: 'The Whisperer',
    heroType: 'YOGA/ENDURANCE',
    hp: 105, attack: 20, defense: 50, speed: 25,
    specialMoves: ['Silent Rep (20/7)', 'Zen Strike (30/5)', 'Quiet Strength (35/5)'],
    weakness: 'Gets startled by loud grunters',
    catchphrase: '...',
    flavorText: 'Nobody knows when they arrived or how much they lift. Moves like a ghost. Respectable.',
    weekKey: 'STARTER-48',
  },
  {
    heroTitle: 'Leg Press Larry',
    heroType: 'STRENGTH/POWER',
    hp: 100, attack: 50, defense: 40, speed: 10,
    specialMoves: ['Quarter Rep (55/3)', 'Plate Stack (40/4)', 'Sled Push (30/6)'],
    weakness: 'Only does quarter reps and calls it a PR',
    catchphrase: 'I leg press 1,000 lbs! *2 inch range of motion*',
    flavorText: 'Larry loads every plate in the gym onto the leg press. Moves it 3 inches. Celebrates.',
    weekKey: 'STARTER-49',
  },
  {
    heroTitle: 'Ab Day Amy',
    heroType: 'CALISTHENICS/HIIT',
    hp: 80, attack: 35, defense: 30, speed: 45,
    specialMoves: ['Crunch Flurry (30/6)', 'Plank to Pike (40/4)', 'Russian Twist (35/5)'],
    weakness: 'Thinks abs come from crunches, not diet',
    catchphrase: 'Abs are made in the gym! ...right?',
    flavorText: 'Does 500 crunches a day but won\'t give up pizza. Respects the hustle though.',
    weekKey: 'STARTER-50',
  },
]
